name: build-and-test
on: [push, workflow_dispatch]
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
          - name: checkout code
            uses: actions/checkout@v3
          - name: install nodejs
            uses: actions/setup-node@v3
            with:
              node-version: 18
          - name: lint code
            run: eslint --ext .jsx --fix src
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: Run Tests
              run: npm tests
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: Build project
              run: npm build
            - name: Deploy project
              run: echo "Project is deployed"

